//+------------------------------------------------------------------+
//| Core/FalconEnums.mqh                                             |
//| R0.2: all 22 enums moved verbatim from the main .mq5.            |
//| Literal move only - no logic change, no renaming.                |
//+------------------------------------------------------------------+
#ifndef FALCON_ENUMS_MQH
#define FALCON_ENUMS_MQH

// --- ENUM_FALCON_ORDER_FAIL_CLASS (moved from main .mq5 lines 844-852) ---
enum ENUM_FALCON_ORDER_FAIL_CLASS
{
   FALCON_FAIL_RETRYABLE = 0,
   FALCON_FAIL_FATAL = 1,
   FALCON_FAIL_NEEDS_REFRESH = 2,
   FALCON_FAIL_BROKER_LIMIT = 3,
   FALCON_FAIL_CONNECTION = 4,
   FALCON_FAIL_UNKNOWN = 5
};

// --- ENUM_FALCON_TSPR_MODE (moved from main .mq5 lines 974-978) ---
enum ENUM_FALCON_TSPR_MODE
{
   FALCON_TSPR_MODE_NORMAL = 0,
   FALCON_TSPR_MODE_MINIMAL_RECOVERY = 1
};

// --- ENUM_FALCON_REPORT_PROFILE (moved from main .mq5 lines 1518-1524) ---
enum ENUM_FALCON_REPORT_PROFILE
{
   FALCON_REPORT_MINIMAL    = 0, // TradeLifecycle + Summary only
   FALCON_REPORT_STANDARD   = 1, // TradeLifecycle + Summary + StrategyRegistry + PeriodManifest
   FALCON_REPORT_DEBUG      = 2, // All diagnostic reports
   FALCON_REPORT_LOCKPARITY = 3  // TradeLifecycle + Summary + LockParity Decomp + Rollup only
};

// --- 19 Core Data Contract enums (moved from main .mq5 lines 1984-2140) ---
enum ENUM_FALCON_DIRECTION
{
   FALCON_DIRECTION_NONE = 0,
   FALCON_DIRECTION_BUY  = 1,
   FALCON_DIRECTION_SELL = -1
};

enum ENUM_FALCON_ENGINE_STATUS
{
   FALCON_ENGINE_DISABLED = 0,
   FALCON_ENGINE_SHADOW   = 1,
   FALCON_ENGINE_PAPER    = 2,
   FALCON_ENGINE_DEMO     = 3,
   FALCON_ENGINE_LIVE     = 4
};

enum ENUM_FALCON_GUARD_STATUS
{
   FALCON_GUARD_NOT_EVALUATED = 0,
   FALCON_GUARD_PASSED        = 1,
   FALCON_GUARD_REJECTED      = 2
};

enum ENUM_FALCON_TRADE_OUTCOME
{
   FALCON_TRADE_OUTCOME_OPEN      = 0,
   FALCON_TRADE_OUTCOME_WIN       = 1,
   FALCON_TRADE_OUTCOME_LOSS      = 2,
   FALCON_TRADE_OUTCOME_BREAKEVEN = 3,
   FALCON_TRADE_OUTCOME_UNKNOWN   = 4
};

enum ENUM_FALCON_TRADE_STAGE
{
   FALCON_TRADE_STAGE_NONE     = 0,
   FALCON_TRADE_STAGE_SHADOW   = 1,
   FALCON_TRADE_STAGE_PAPER    = 2,
   FALCON_TRADE_STAGE_DEMO     = 3,
   FALCON_TRADE_STAGE_LIVE     = 4
};


enum ENUM_FALCON_SHADOW_RECORD_STATUS
{
   FALCON_SHADOW_RECORD_NONE      = 0,
   FALCON_SHADOW_RECORD_STAGED    = 1,
   FALCON_SHADOW_RECORD_CLOSED    = 2,
   FALCON_SHADOW_RECORD_CANCELLED = 3
};


enum ENUM_FALCON_EVIDENCE_TYPE
{
   FALCON_EVIDENCE_TYPE_NONE                = 0,
   FALCON_EVIDENCE_TYPE_CANDLE_PATTERN      = 1,
   FALCON_EVIDENCE_TYPE_CHART_PATTERN       = 2,
   FALCON_EVIDENCE_TYPE_OBJECTIVE_INDICATOR = 3,
   FALCON_EVIDENCE_TYPE_SMC_LIQUIDITY       = 4
};

enum ENUM_FALCON_EVIDENCE_STATE
{
   FALCON_EVIDENCE_STATE_NOT_EVALUATED = 0,
   FALCON_EVIDENCE_STATE_ABSENT        = 1,
   FALCON_EVIDENCE_STATE_PRESENT       = 2,
   FALCON_EVIDENCE_STATE_CONFLICTING   = 3
};

enum ENUM_FALCON_RUNTIME_SAFETY_STATUS
{
   FALCON_RUNTIME_SAFETY_NOT_EVALUATED = 0,
   FALCON_RUNTIME_SAFETY_PASSED        = 1,
   FALCON_RUNTIME_SAFETY_REJECTED      = 2
};

enum ENUM_FALCON_LOOKAHEAD_RISK
{
   FALCON_LOOKAHEAD_RISK_NONE              = 0,
   FALCON_LOOKAHEAD_RISK_CURRENT_CANDLE    = 1,
   FALCON_LOOKAHEAD_RISK_FINAL_STATE       = 2,
   FALCON_LOOKAHEAD_RISK_INVALID_CANDLE    = 3,
   FALCON_LOOKAHEAD_RISK_INVALID_TRADEPLAN = 4
};

enum ENUM_FALCON_STRATEGY_GROUP
{
   FALCON_STRATEGY_GROUP_CORE         = 0,
   FALCON_STRATEGY_GROUP_PRICE_ACTION = 1,
   FALCON_STRATEGY_GROUP_OPENING      = 2,
   FALCON_STRATEGY_GROUP_LIQUIDITY    = 3,
   FALCON_STRATEGY_GROUP_CONFIRMATION = 4,
   FALCON_STRATEGY_GROUP_RESEARCH     = 5
};

enum ENUM_FALCON_ENGINE_HEALTH
{
   FALCON_ENGINE_HEALTH_DISABLED    = 0,
   FALCON_ENGINE_HEALTH_RESEARCH    = 1,
   FALCON_ENGINE_HEALTH_WATCH       = 2,
   FALCON_ENGINE_HEALTH_HEALTHY     = 3,
   FALCON_ENGINE_HEALTH_CORE_WINNER = 4,
   FALCON_ENGINE_HEALTH_LOCKED      = 5
};

enum ENUM_FALCON_ADAPTER_STATUS
{
   FALCON_ADAPTER_STATUS_NOT_INITIALIZED           = 0,
   FALCON_ADAPTER_STATUS_NO_TRADE                  = 1,
   FALCON_ADAPTER_STATUS_SHADOW_CANDIDATE_BLOCKED  = 2,
   FALCON_ADAPTER_STATUS_READY                     = 3
};


enum ENUM_FALCON_DETECTOR_STATUS
{
   FALCON_DETECTOR_STATUS_NOT_INITIALIZED      = 0,
   FALCON_DETECTOR_STATUS_NO_TRADE             = 1,
   FALCON_DETECTOR_STATUS_BLOCKED              = 2,
   FALCON_DETECTOR_STATUS_READY_STUB           = 3,
   FALCON_DETECTOR_STATUS_NO_FVG               = 4,
   FALCON_DETECTOR_STATUS_FVG_FOUND_SHADOW_ONLY= 5
};

enum ENUM_FALCON_CANDIDATE_STATUS
{
   FALCON_CANDIDATE_STATUS_NOT_INITIALIZED = 0,
   FALCON_CANDIDATE_STATUS_NO_CANDIDATE    = 1,
   FALCON_CANDIDATE_STATUS_BLOCKED         = 2,
   FALCON_CANDIDATE_STATUS_READY_SHADOW    = 3
};

enum ENUM_FALCON_RETEST_WATCHER_STATUS
{
   FALCON_RETEST_WATCHER_STATUS_NOT_INITIALIZED = 0,
   FALCON_RETEST_WATCHER_STATUS_BLOCKED         = 1,
   FALCON_RETEST_WATCHER_STATUS_WAITING         = 2,
   FALCON_RETEST_WATCHER_STATUS_RETEST_TOUCHED  = 3,
   FALCON_RETEST_WATCHER_STATUS_SKELETON_READY  = 4
};

enum ENUM_FALCON_TRADEPLAN_STAGING_STATUS
{
   FALCON_TRADEPLAN_STAGING_STATUS_NOT_INITIALIZED = 0,
   FALCON_TRADEPLAN_STAGING_STATUS_BLOCKED         = 1,
   FALCON_TRADEPLAN_STAGING_STATUS_PLAN_CREATED    = 2,
   FALCON_TRADEPLAN_STAGING_STATUS_STAGED_SHADOW   = 3
};

enum ENUM_FALCON_SHADOW_LIFECYCLE_STATUS
{
   FALCON_SHADOW_LIFECYCLE_STATUS_NOT_INITIALIZED = 0,
   FALCON_SHADOW_LIFECYCLE_STATUS_BLOCKED         = 1,
   FALCON_SHADOW_LIFECYCLE_STATUS_MONITORING      = 2,
   FALCON_SHADOW_LIFECYCLE_STATUS_CLOSED_TP       = 3,
   FALCON_SHADOW_LIFECYCLE_STATUS_CLOSED_SL       = 4,
   FALCON_SHADOW_LIFECYCLE_STATUS_CLOSED_TIMEOUT  = 5
};

// --- ENUM_FALCON_BROKER_TM_EVENT_TYPE (moved from main .mq5 lines 3041-3061) ---
enum ENUM_FALCON_BROKER_TM_EVENT_TYPE
{
   FALCON_BTM_EVENT_ENTRY_PLANNED = 0,
   FALCON_BTM_EVENT_ENTRY_ACCEPTED_PAPER = 1,
   FALCON_BTM_EVENT_TP1_TOUCH = 2,
   FALCON_BTM_EVENT_TP2_TOUCH = 3,
   FALCON_BTM_EVENT_PROTECTION_ARMED = 4,
   FALCON_BTM_EVENT_PROTECTION_TRIGGERED = 5,
   FALCON_BTM_EVENT_RUNNER_ARMED = 6,
   FALCON_BTM_EVENT_RUNNER_EXIT = 7,
   FALCON_BTM_EVENT_RAW_SL_HIT = 8,
   FALCON_BTM_EVENT_TIMEOUT_CLOSE = 9,
   FALCON_BTM_EVENT_FINAL_CLOSE = 10,
   FALCON_BTM_EVENT_ACCOUNTING_ONLY_ADJUSTMENT = 11,
   FALCON_BTM_EVENT_BAR_ORDER_AMBIGUOUS = 12,
   FALCON_BTM_EVENT_FOUNDATION_NO_RUNTIME_EVENT = 13,
   FALCON_BTM_EVENT_EVENT_TIMELINE_AUDIT = 14,
   FALCON_BTM_EVENT_BROKER_ENTRY_ATTEMPTED = 15,
   FALCON_BTM_EVENT_BROKER_ENTRY_ACCEPTED = 16,
   FALCON_BTM_EVENT_BROKER_ENTRY_REJECTED = 17
};

#endif // FALCON_ENUMS_MQH
